# Generated by Django 4.1.1 on 2022-10-11 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0008_alter_loja_loja_admin'),
        ('roupas', '0007_roupa_t1_roupa_t2_roupa_t3_roupa_t4_roupa_t5_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(default=django.utils.timezone.now)),
                ('colecao_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecoes.colecao')),
                ('loja_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
                ('roupa_pedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupas.roupa')),
                ('usuario_pedinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
