# Generated by Django 4.1.1 on 2022-10-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
        ('roupas', '0002_roupa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='colecao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colecoes.colecao'),
        ),
    ]
