# Generated by Django 4.1.1 on 2022-10-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0005_categoria_roupa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roupas.categoria'),
        ),
    ]
