# Generated by Django 4.1.1 on 2022-10-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0007_roupa_t1_roupa_t2_roupa_t3_roupa_t4_roupa_t5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_tamanho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='roupas.tipotamanho'),
        ),
    ]
