# Generated by Django 4.1.1 on 2022-10-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0008_tipotamanho_categoria_tipo_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='qtd_estoque',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
