# Generated by Django 4.1.1 on 2022-10-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
        ('roupas', '0009_alter_roupa_qtd_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='colecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecoes.colecao'),
        ),
    ]
