# Generated by Django 4.1.1 on 2022-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0011_alter_roupa_g_alter_roupa_gg_alter_roupa_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='qtd_estoque',
        ),
    ]
