# Generated by Django 4.1.1 on 2022-10-11 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0012_remove_roupa_qtd_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='data_adicao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
