# Generated by Django 4.1.1 on 2022-10-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
        ('roupas', '0013_roupa_data_adicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='roupas.categoria'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='colecao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colecoes.colecao'),
        ),
    ]
