# Generated by Django 4.1.1 on 2022-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='logo_loja',
            field=models.ImageField(null=True, upload_to='logos_lojas/'),
        ),
    ]
