# Generated by Django 4.1.1 on 2022-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_plano_loja_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email_loja',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
