# Generated by Django 4.1.1 on 2022-10-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_loja_telefone_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cvv',
            field=models.CharField(max_length=64),
        ),
    ]
