# Generated by Django 4.1.1 on 2022-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_usuario',
            field=models.ImageField(null=True, upload_to='fotos_usuarios/'),
        ),
    ]
