# Generated by Django 4.1.1 on 2022-10-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loja_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('cep_loja', models.CharField(max_length=9)),
                ('estado_loja', models.CharField(max_length=100)),
                ('cidade_loja', models.CharField(max_length=100)),
                ('rua_loja', models.CharField(max_length=100)),
                ('bairro_loja', models.CharField(max_length=100)),
                ('numero_cartao', models.CharField(max_length=15)),
                ('nome_cartao', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=50)),
                ('data_expiracao', models.DateTimeField()),
                ('date_joined_loja', models.DateTimeField(default=django.utils.timezone.now)),
                ('loja_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
