# Generated by Django 4.1.1 on 2022-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_loja_admin_alter_user_telefone_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
