# Generated by Django 4.1.1 on 2022-10-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
